configfile: "configs/config.yaml"


include: "common/Snakefile"
include: "common/Snakefile"
include: "gm12878/Snakefile"


rule all:
    input:
        expand(config['short_rnaseq']['merged_bam'], sample='gm12878')
