configfile: "configs/config.yaml"


include: "download/Snakefile"
include: "common/Snakefile"
include: "align/Snakefile"
include: "long_reads/Snakefile"
include: "correction/Snakefile"
include: "benchmark/Snakefile"
include: "c2c12/Snakefile"
# include: "plot/Snakefile"
# include: "short_rnaseq/Snakefile"

rule all:
    input:
        rules.all_correction.input
