rule download_fasta_mm10:
    output:
        config['genome']['fasta']['mm10']
    shell:
        "wget -O - https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M25/GRCm38.primary_assembly.genome.fa.gz | gunzip -c > {output}"


rule download_gtf_mm10:
    output:
        config['genome']['gtf_raw']['mm10']
    shell:
        "wget -O - https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M25/gencode.vM25.annotation.gtf.gz | gunzip -c > {output}"
