
rule lapa_longreads_pilot:
    input:
        alignment = config['pilot']['read_annot'],
        fasta = config['human']['fasta'],
        gtf = config['human']['gtf'],
        chrom_sizes = config['common']['chrom_sizes'].format(specie='human')
    threads: 1
    resources:
        mem_gb = 16
    output:
        directory(config['lapa']['long_rna_dir'].format(sample='pilot'))
    shell:
        "lapa \
        --alignment {input.alignment} \
        --fasta {input.fasta} \
        --annotation {input.gtf} \
        --chrom_sizes {input.chrom_sizes} \
        --output_dir {output}"


rule lapa_pilot_atlas:
    input:
        long_reads = config['lapa']['long_rna_dir'].format(sample='pilot')
    threads: 1
    resources:
        mem_gb = 16
    output:
        heatmap = '../../reports/figures/pilot_heatmap.png'
    shell:
        "lapa \
        --alignment {input.alignment} \
        --fasta {input.fasta} \
        --annotation {input.gtf} \
        --chrom_sizes {input.chrom_sizes} \
        --output_dir {output}"
